// M9 — Full-fidelity React export.
//
// The pre-M9 exporter reverse-mapped base-breakpoint styles to Tailwind and
// dropped media queries + pseudo-states + expressions (WS-PARITY-AUDIT #6). A
// faithful reverse-map of arbitrary CSS to Tailwind is impossible, so this emits
// a self-contained component that carries data-ws-id / data-ws-component on every
// element and injects the SAME full-fidelity stylesheet the canvas paints
// (via lib/publish/cssGen). Bound props are resolved to literals (expressionGen).

import {
  type WebstudioData,
  type WsComponentMeta,
} from "@webstudio-is/sdk";
import { generateCss } from "./publish/cssGen";
import { resolveProps } from "./publish/expressionGen";

// Stable public attribute names — matching the generated CSS selectors (cssGen).
const idAttribute = "data-ws-id";
const componentAttribute = "data-ws-component";

const TAG: Record<string, string> = {
  Box: "div", Body: "div", Section: "section", Article: "article",
  Aside: "aside", Header: "header", Footer: "footer", Main: "main",
  Nav: "nav", Paragraph: "p", Heading: "h2", Text: "span",
  Bold: "strong", Italic: "em", Link: "a", RichTextLink: "a",
  Button: "button", Image: "img", Form: "form", WebhookForm: "form",
  Input: "input", Textarea: "textarea", Select: "select", Label: "label",
  List: "ul", ListItem: "li", Separator: "hr",
};

const VOID_TAGS = new Set(["img", "input", "hr", "br"]);

function jsxProp(name: string): string {
  if (name === "class") return "className";
  if (name === "for") return "htmlFor";
  if (name === "style") return "style"; // handled specially below
  return name;
}

function componentName(projectName: string): string {
  const cleaned = projectName.replace(/[^a-zA-Z0-9]/g, " ").split(" ").filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1)).join("");
  return /^[A-Z]/.test(cleaned) ? cleaned : `Page${cleaned}`;
}

export function exportToReact(
  data: WebstudioData,
  projectName = "Page",
  metas: Map<string, WsComponentMeta> = new Map()
): string {
  const propMap = resolveProps(data.props, data.dataSources);
  const css = generateCss(data, metas);
  const fullCss = [css.fonts, css.presets, css.user].filter(Boolean).join("\n");

  function renderInst(iId: string, indent: number): string {
    const inst = data.instances.get(iId);
    if (!inst) return "";
    const tag = TAG[inst.component] ?? "div";
    const pad = "  ".repeat(indent);
    const ip = propMap.get(iId) ?? {};

    const attrs: string[] = [
      `${jsxProp(idAttribute)}="${iId}"`,
      `${jsxProp(componentAttribute)}="${inst.component}"`,
    ];

    for (const [k, v] of Object.entries(ip)) {
      if (k === "children") continue;
      if (k === "style" && typeof v === "string") {
        // inline style string → JSX style object is non-trivial; keep as data attr
        attrs.push(`data-style={${JSON.stringify(v)}}`);
        continue;
      }
      if (typeof v === "boolean") { if (v) attrs.push(jsxProp(k)); }
      else attrs.push(`${jsxProp(k)}={${JSON.stringify(String(v))}}`);
    }

    const attrStr = " " + attrs.join(" ");
    if (VOID_TAGS.has(tag)) return `${pad}<${tag}${attrStr} />\n`;

    const children = inst.children
      .map((c) => {
        if (c.type === "text") return `${pad}  ${c.value}\n`;
        if (c.type === "id") return renderInst(c.value, indent + 1);
        return "";
      })
      .join("");

    if (!children.trim()) return `${pad}<${tag}${attrStr} />\n`;
    return `${pad}<${tag}${attrStr}>\n${children}${pad}</${tag}>\n`;
  }

  const home = data.pages.pages.get(data.pages.homePageId);
  const rootInst = home ? data.instances.get(home.rootInstanceId) : undefined;
  const body = rootInst
    ? rootInst.children
        .map((c) => (c.type === "id" ? renderInst(c.value, 3) : c.type === "text" ? `      ${c.value}\n` : ""))
        .join("")
    : "      {/* No content */}\n";

  const name = componentName(projectName);
  const rootAttrs = home
    ? ` ${jsxProp(idAttribute)}="${home.rootInstanceId}" ${jsxProp(componentAttribute)}="Body"`
    : "";

  return `// Generated by Nova — WebstudioData → React (full-fidelity)
// The stylesheet below carries media queries, pseudo-states and the source cascade.
import React from "react";

const css = ${JSON.stringify(fullCss)};

export default function ${name}() {
  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: css }} />
      <div${rootAttrs}>
${body}      </div>
    </>
  );
}
`;
}
